const SET_NUMBER_OF_BLOCKS = 'SET_NUMBER_OF_BLOCKS';
const GET_BLOCKS = 'GET_BLOCKS';
const GET_BLOCKS_PENDING = 'GET_BLOCKS_PENDING';
const GET_BLOCKS_SUCCESS = 'GET_BLOCKS_SUCCESS';

export {
  SET_NUMBER_OF_BLOCKS,
  GET_BLOCKS,
  GET_BLOCKS_PENDING,
  GET_BLOCKS_SUCCESS,
};