const SET_NUMBER_OF_BLOCKS = 'SET_NUMBER_OF_BLOCKS';
const GET_BLOCKS = 'GET_BLOCKS';
const GET_BLOCKS_PENDING = 'GET_BLOCKS_PENDING';
const GET_BLOCKS_SUCCESS = 'GET_BLOCKS_SUCCESS';
const SET_ACTIVE_BLOCK = 'SET_ACTIVE_BLOCK';
const SET_ACTIVE_TRANSACTION = 'SET_ACTIVE_TRANSACTION';
const GET_TRANSACTION_RECEIPT = 'GET_TRANSACTION_RECEIPT';
const GET_TRANSACTION_RECEIPT_PENDING = 'GET_TRANSACTION_RECEIPT_PENDING';
const GET_TRANSACTION_RECEIPT_SUCCESS = 'GET_TRANSACTION_RECEIPT_SUCCESS';

export {
  SET_NUMBER_OF_BLOCKS,
  GET_BLOCKS,
  GET_BLOCKS_PENDING,
  GET_BLOCKS_SUCCESS,
  SET_ACTIVE_BLOCK,
  SET_ACTIVE_TRANSACTION,
  GET_TRANSACTION_RECEIPT,
  GET_TRANSACTION_RECEIPT_PENDING,
  GET_TRANSACTION_RECEIPT_SUCCESS,
};